services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: coffee-shop-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: QuanLyCafe
      MYSQL_USER: coffee_user
      MYSQL_PASSWORD: coffee_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker-init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - coffee-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # User Service
  user-service:
    build: 
      context: ./services/user-service
      dockerfile: Dockerfile
    container_name: coffee-user-service
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=QuanLyCafe
      - DB_USER=coffee_user
      - DB_PASSWORD=coffee_pass
      - JWT_SECRET=your-secret-key-here
    ports:
      - "3001:3001"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - coffee-network
    restart: unless-stopped

  # Menu Service
  menu-service:
    build: 
      context: ./services/menu-service
      dockerfile: Dockerfile
    container_name: coffee-menu-service
    environment:
      - NODE_ENV=development
      - PORT=3002
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=QuanLyCafe
      - DB_USER=coffee_user
      - DB_PASSWORD=coffee_pass
    ports:
      - "3002:3002"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - coffee-network
    restart: unless-stopped

  # Table Service
  table-service:
    build: 
      context: ./services/table-service
      dockerfile: Dockerfile
    container_name: coffee-table-service
    environment:
      - NODE_ENV=development
      - PORT=3003
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=QuanLyCafe
      - DB_USER=coffee_user
      - DB_PASSWORD=coffee_pass
    ports:
      - "3003:3003"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - coffee-network
    restart: unless-stopped

  # Billing Service
  billing-service:
    build: 
      context: ./services/billing-service
      dockerfile: Dockerfile
    container_name: coffee-billing-service
    environment:
      - NODE_ENV=development
      - PORT=3004
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=QuanLyCafe
      - DB_USER=coffee_user
      - DB_PASSWORD=coffee_pass
    ports:
      - "3004:3004"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - coffee-network
    restart: unless-stopped

  # API Gateway
  api-gateway:
    build: 
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: coffee-api-gateway
    environment:
      - NODE_ENV=development
      - PORT=3000
      - USER_SERVICE_URL=http://user-service:3001
      - MENU_SERVICE_URL=http://menu-service:3002
      - TABLE_SERVICE_URL=http://table-service:3003
      - BILLING_SERVICE_URL=http://billing-service:3004
      - JWT_SECRET=your-secret-key-here
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - menu-service
      - table-service
      - billing-service
    networks:
      - coffee-network
    restart: unless-stopped

  # Frontend
  frontend:
    build: 
      context: ./front-end
      dockerfile: Dockerfile
    container_name: coffee-frontend
    environment:
      - VITE_API_URL=http://localhost:3000
    ports:
      - "5173:5173"
    depends_on:
      - api-gateway
    networks:
      - coffee-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  coffee-network:
    driver: bridge
